### ISSUE TITLE
Dark skin render with transparecy

### ISSUE THREAD

**Issue by Carlosjrlu** [ErickSkrauch/SkinRenderer2D#1]
With the addition of the black base for transparency, skins with transparecy look dark instead of the desired color.

With this skin:
![cosmocorban-e44e6628](https://user-images.githubusercontent.com/20954701/107906946-62abe080-6f20-11eb-8f2a-c1af5c186baf.png)

Instead of getting this:
![CosmoCorban (1)](https://user-images.githubusercontent.com/20954701/107906956-6d667580-6f20-11eb-97d5-29fe697b8c83.png)

I get this on my profile
![skins-renderer](https://user-images.githubusercontent.com/20954701/107907279-42305600-6f21-11eb-9fc8-2e2f0bcdbc2b.png)

And this is the full 2d render
![skins-renderer (1)](https://user-images.githubusercontent.com/20954701/107907325-63914200-6f21-11eb-945b-7514aec83afe.png)

**Comment by erickskrauch** [comment]
@Carlosjrlu, can you please give me a link to the skin in the Ely.by's skins catalog?

**Comment by Carlosjrlu** [comment]
Here:
https://ely.by/skins/s1636889

**Comment by erickskrauch** [comment]
Thank you. I will investigate the problem and write back with the results.

**Comment by erickskrauch** [comment]
@Carlosjrlu, does this seems right?
![fixed skin preview](https://user-images.githubusercontent.com/4787256/108059323-9f2d2880-7055-11eb-9116-8e975736f241.png)

**Comment by Carlosjrlu** [comment]
Yeah! That's exactly how it should look.

**Comment by erickskrauch** [comment]
Great. I need a little more time to fix a few more edge cases, but essentially, we fixed the key problem.
